Update StylusUtils.cpp
lectureStudio/stylus pull request #2
Opened 2021-05-04 02:09 UTC by yenon

Added branching for predefined types, should introduce compatibility with jetpack compose and window frameworks exposing the window handle as a java.lang.Long, atleast on JNI side.

Be aware that i have never written anything complicated in C++ or with JNI, but this seems to work in all samples and 2 new test cases i made for my project.

2021-05-06 14:50 UTC, devopvoid commented
Thanks! Let me test it.

Does this library even work with Android? May I ask what project you are working on?

2021-05-06 15:45 UTC, yenon commented
It does not work with Android, i should have clarified this a bit more. What i mean is Jetpack Compose Desktop, based on Jetpack Compose. Since Compose basically renders on a Canvas, ignoring the Android view system, you can relatively easily use it on Desktop aswell, by just providing a Canvas to render to.
The project is somewhat similar to lectureStudio, but for taking notes on a infinite whiteboard.

2021-05-12 18:14 UTC, devopvoid requested changes
Works for me, except with one additional change. `StylusUtils.h` requires the following definition:

`long GetComposeWindowId(JNIEnv * env, const jni::JavaLocalRef<jobject> & window);`

Thanks again! Could you please add this change to this PR. I'll merge then. Do you need the changes to be pushed with a new version to Maven Central?

2021-05-14 01:32 UTC, yenon commented
Yeah, I just committed using the web client, not my IDE. Which boils down to me forgetting the header, I already have that modification in the IDE. I personally don't need the changes pushed, but someone else might. There is a few other loose ends in your library I might tackle later, mainly the StylusListener needing a long called nativeHandle to actually function, which doesn't seem too logical from a java only perspective, as that should be hidden from the user of the library.

2021-05-14 09:04 UTC, merged

2021-05-14 09:08 UTC, devopvoid commented
Thanks!

> There is a few other loose ends in your library I might tackle later

Any help, bug fix, improvement or feature request is welcome 😃